#!/usr/bin/with-contenv sh

TZ=${TZ:-"Asia/Shanghai"}

ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
echo $TZ > /etc/timezone

PUID=${PUID:-${TC_UID}}
PGID=${PGID:-${TC_UID}}

sed -i -e "s/${TC_USER}:x:${TC_UID}/${TC_USER}:x:$PGID/" /etc/group
sed -i -e "s/${TC_USER}:x:${TC_UID}:${TC_UID}/${TC_USER}:x:$PUID:$PGID/" /etc/passwd
