#!/usr/bin/with-contenv sh

PUID=${PUID:-${TC_PID}}
PGID=${PGID:-${TC_PID}}

sed -i -e "s/${TC_USER}:x:${TC_PID}/${TC_USER}:x:$PGID/" /etc/group
sed -i -e "s/${TC_USER}:x:${TC_PID}:${TC_PID}/${TC_USER}:x:$PUID:$PGID/" /etc/passwd

chown -R ${TC_USER}:${TC_USER} /defaults
chown -R ${TC_USER}:${TC_USER} /srv
